name: First Interaction

on: [pull_request, issues]

jobs:
  first-interaction:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello @${{ github.actor }}, thanks for opening your first issue ğŸ˜Š! We really appreciate your work. Happy Coding ğŸ‰ğŸŠ !'
        pr-message: 'Hello @${{ github.actor }}, thanks for opening your first pull request ğŸ˜Š! We really appreciate your work. Happy Coding ğŸ‰ğŸŠ !'
